// File: src/main/kotlin/com/kasir/models/SupplierTable.kt
package com.kasir.models

import org.jetbrains.exposed.dao.id.UUIDTable
import org.jetbrains.exposed.sql.ReferenceOption
import org.jetbrains.exposed.sql.*

/**
 * Table definition for Supplier using UUID primary key.
 */
object SupplierTable : UUIDTable(name = "supplier") {
    // UUID primary key 'id' auto-generated by UUIDTable

    // Nama supplier (varchar, not null)
    val namaSupplier = varchar("nama_supplier", 255)

    // Kontak supplier, optional
    val no_hp      = varchar("no_hp", 100).nullable()

    // Alamat supplier, optional text
    val alamat       = text("alamat").nullable()

    // Rekening bank supplier, optional
    val rekeningBank = varchar("rekening_bank", 100).nullable()

    // Nama sales yang bertanggung jawab, optional
    val namaSales    = varchar("nama_sales", 255).nullable()
}
